"use client";

import Link from "next/link";
import {
  ArrowRight,
  Brush,
  CheckCircle2,
  ShieldCheck,
  Sparkles,
  Truck,
} from "lucide-react";
import { useQuery } from "@tanstack/react-query";

import { FrameCard } from "@/components/shop/FrameCard";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { getFrames } from "@/lib/api";

const workflow = [
  {
    title: "Pick your frame",
    detail: "Choose size and layout from curated templates.",
    icon: Sparkles,
  },
  {
    title: "Customize every slot",
    detail: "Upload one or multiple photos and assign them precisely.",
    icon: Brush,
  },
  {
    title: "Checkout securely",
    detail: "Pay via Razorpay with UPI, cards, and other supported methods.",
    icon: ShieldCheck,
  },
  {
    title: "Track delivery",
    detail: "Follow order status updates from received to dispatched.",
    icon: Truck,
  },
];

const trustHighlights = [
  "Clear pricing with offer visibility on every product",
  "Customer support via email and WhatsApp",
  "Dedicated pages for shipping, returns, privacy, and terms",
];

export default function HomePage() {
  const { data, isLoading, error } = useQuery({
    queryKey: ["frames", "featured"],
    queryFn: () => getFrames({ active_only: true }),
  });

  const featured = (data ?? []).slice(0, 4);

  return (
    <div className="container-shell py-10 sm:py-14">
      <section className="grid gap-8 rounded-3xl border border-stone-200 bg-white/80 p-8 shadow-sm backdrop-blur dark:border-stone-800 dark:bg-stone-900/70 lg:grid-cols-2 lg:p-10">
        <div>
          <div className="inline-flex items-center rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-medium text-amber-900 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-200">
            <Sparkles className="mr-2 h-3.5 w-3.5" />
            Premium Custom Frame Studio
          </div>
          <h1 className="mt-4 text-4xl font-semibold leading-tight sm:text-5xl">
            Turn everyday photos into crafted wall stories.
          </h1>
          <p className="mt-4 max-w-xl text-stone-600 dark:text-stone-300">
            Browse curated frame templates, customize each photo slot with live editing, then
            place your print order in minutes.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Button asChild size="lg">
              <Link href="/shop">
                Start Shopping
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button variant="outline" size="lg" asChild>
              <Link href="/orders">Track Orders</Link>
            </Button>
          </div>
        </div>

        <div className="rounded-2xl border border-stone-200 bg-gradient-to-br from-amber-100 to-stone-100 p-6 dark:border-stone-800 dark:from-amber-900/40 dark:to-stone-900">
          <p className="text-sm text-stone-700 dark:text-stone-300">Why BabyTint?</p>
          <ul className="mt-3 space-y-3 text-sm">
            <li>Live frame preview with slot-by-slot upload and guided crop.</li>
            <li>Admin-managed frame templates with up to 24 collage slots.</li>
            <li>Secure Razorpay checkout and order timeline tracking.</li>
            <li>300 DPI print-ready output generated by backend compositor.</li>
          </ul>
        </div>
      </section>

      <section className="mt-12">
        <div className="mb-5 flex items-center justify-between">
          <h2 className="text-2xl font-semibold">Featured Frames</h2>
          <Link href="/shop" className="text-sm font-medium text-amber-700">
            View all
          </Link>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {isLoading
            ? Array.from({ length: 4 }).map((_, index) => (
                <div key={index} className="space-y-3">
                  <Skeleton className="aspect-[4/5] rounded-2xl" />
                  <Skeleton className="h-5 w-2/3" />
                  <Skeleton className="h-4 w-1/2" />
                </div>
              ))
            : featured.map((frame) => <FrameCard key={frame.id} frame={frame} />)}
        </div>
        {!isLoading && error ? (
          <p className="mt-4 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-300">
            Could not load frames from backend. Please check API is running on port 8000.
          </p>
        ) : null}
        {!isLoading && !error && featured.length === 0 ? (
          <p className="mt-4 rounded-xl border border-stone-200 bg-stone-50 px-3 py-2 text-sm text-stone-600 dark:border-stone-700 dark:bg-stone-900/40 dark:text-stone-300">
            No active frame templates found yet.
          </p>
        ) : null}
      </section>

      <section className="mt-14">
        <div className="mb-5 flex items-center justify-between">
          <h2 className="text-2xl font-semibold">How It Works</h2>
          <Link href="/about" className="text-sm font-medium text-amber-700">
            Learn more
          </Link>
        </div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {workflow.map((step) => {
            const Icon = step.icon;
            return (
              <article
                key={step.title}
                className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"
              >
                <div className="inline-flex rounded-full border border-amber-200 bg-amber-50 p-2 text-amber-700 dark:border-amber-800 dark:bg-amber-900/30 dark:text-amber-200">
                  <Icon className="h-4 w-4" />
                </div>
                <h3 className="mt-3 text-lg font-semibold">{step.title}</h3>
                <p className="mt-2 text-sm text-stone-600 dark:text-stone-300">{step.detail}</p>
              </article>
            );
          })}
        </div>
      </section>

      <section className="mt-8 rounded-3xl border border-stone-200 bg-gradient-to-br from-stone-50 to-amber-50 p-7 dark:border-stone-800 dark:from-stone-900 dark:to-stone-900 sm:p-9">
        <h2 className="text-2xl font-semibold">Built for confident online buying</h2>
        <div className="mt-4 grid gap-3 md:grid-cols-3">
          {trustHighlights.map((item) => (
            <div
              key={item}
              className="flex items-start gap-2 rounded-xl border border-stone-200 bg-white/80 p-4 text-sm dark:border-stone-700 dark:bg-stone-900/50"
            >
              <CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-600" />
              <span className="text-stone-700 dark:text-stone-200">{item}</span>
            </div>
          ))}
        </div>
        <div className="mt-6 flex flex-wrap gap-3">
          <Button variant="outline" asChild>
            <Link href="/shipping-returns">Shipping & Returns</Link>
          </Button>
          <Button variant="outline" asChild>
            <Link href="/privacy">Privacy</Link>
          </Button>
          <Button variant="outline" asChild>
            <Link href="/terms">Terms</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
